# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  username: postgres
  password: 123456

production:
  <<: *default
  database: test-orm

development:
  <<: *default
  database: test-orm


test:
  <<: *default
  database: test-orm
